### ISSUE TITLE
How to create an Broken Workitem through Version One API

### ISSUE THREAD

**Issue by srikumaran89** [versionone/scripts#4]
I tried to post the below XML to the REST API, but wasn't successful.
Please advice

Post to:
   `https://www13.v1host.com/Platts/Account.mvc/LogIn/rest-1.v1/Data//Defect/<DefectID>`
  Content-Type: application/xml

Payload body:

```
<Asset>
<Relation name="AffectedPrimaryWorkitems" act="add"><Asset idref="Story:Number" /></Relation>
<Relation name="Scope" act="set"><Asset idref="Scope:Number" /></Relation>
</Asset>
```

**Comment by kgargano** [comment]
Sri, the URL you provided appears to be a redirected url to the login page.  Make sure that you've logged into your instance and are hitting Platts/rest-1.v1/Data/Defect/<DefectID> rather than the account.mvc/LogIn url.  Does that help?

**Comment by srikumaran89** [comment]
@kgargano No it didn't help. When i posting the XML, i not getting any error but the story is not added in the Broken workitem.

**Comment by pmamut** [comment]
Sri, since `AffectedPrimaryWorkitems` relation is multi-value, they syntax you need to use to add related assets is slightly different from single-value relations such as `Scope`. The `act="add"` attribute goes onto each `Asset` node under `Relation`, not the `Relation` node itself. Hope this helps.

**Comment by srikumaran89** [comment]
@pmamut thanks a lot it work now!!! :+1:
